"""
run_queries.py
---------------
Runs every .sql file in sql/queries/ against data/ecommerce.db and writes a
single markdown report (docs/query_results.md) with each query's SQL and a
preview of its actual output. Used to keep the README's example output
honest -- it's generated from a real run, not hand-typed.
"""

import glob
import sqlite3
import re

DB_PATH = "data/ecommerce.db"
QUERY_GLOB = "sql/queries/*.sql"
OUT_PATH = "docs/query_results.md"
MAX_ROWS_SHOWN = 10


def strip_leading_comment_block(sql_text):
    """Return (comment_lines, sql_only) split at the first non-comment/blank line."""
    lines = sql_text.splitlines()
    comment_lines = []
    i = 0
    while i < len(lines) and (lines[i].strip().startswith("--") or lines[i].strip() == ""):
        comment_lines.append(lines[i])
        i += 1
    return "\n".join(comment_lines).strip(), "\n".join(lines[i:]).strip()


def markdown_table(columns, rows):
    header = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join(["---"] * len(columns)) + " |"
    body = []
    for row in rows[:MAX_ROWS_SHOWN]:
        body.append("| " + " | ".join("" if v is None else str(v) for v in row) + " |")
    return "\n".join([header, sep] + body)


def main():
    conn = sqlite3.connect(DB_PATH)
    files = sorted(glob.glob(QUERY_GLOB))

    out = ["# Query Results\n", "Generated by `scripts/run_queries.py` against `data/ecommerce.db`. "
           "Each section shows the leading comment block (business question + technique), "
           f"the query, and the first {MAX_ROWS_SHOWN} rows of real output.\n"]

    for path in files:
        with open(path) as f:
            sql_text = f.read()

        comment, sql_only = strip_leading_comment_block(sql_text)
        title = comment.splitlines()[0].replace("-- Business question:", "").strip() if comment else path

        out.append(f"\n## `{path.split('/')[-1]}`\n")
        out.append(f"**Question:** {title}\n")
        out.append("```sql\n" + sql_text.strip() + "\n```\n")

        try:
            cur = conn.execute(sql_only)
            cols = [d[0] for d in cur.description]
            rows = cur.fetchall()
            out.append(f"**Result** ({len(rows)} row(s), showing up to {MAX_ROWS_SHOWN}):\n")
            out.append(markdown_table(cols, rows) + "\n")
        except Exception as e:
            out.append(f"**ERROR running query:** {e}\n")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(out))

    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
